### ISSUE TITLE
No useful metadata

### ISSUE THREAD

**Issue by alaninmcr** [ibisba/RetroPath2-cwl#1]
workflow.knime does not contain any useful metadata such as name or description.

Similarly there is nothing very useful in workflowset.meta

**Comment by stelfrich** [comment]
d90a1ba5de5a0edc5fd278da0385de175e0da7ed adds more information (as much as is possible now) to [`workflowset.meta`](https://github.com/ibisba/RetroPath2-cwl/blob/d90a1ba5de5a0edc5fd278da0385de175e0da7ed/workflow/workflowset.meta).
